name: Build and Push to Nexus

on:
  push:
    branches:
      - main # Or the branch you want to trigger the workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change this to the appropriate Java version

      - name: Build and package with Maven
        run: mvn clean package

      - name: Publish to Nexus
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
